# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/svenstaro/prj/innojam9

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/svenstaro/prj/innojam9/build-web

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/svenstaro/prj/innojam9/build-web/CMakeFiles /home/svenstaro/prj/innojam9/build-web/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/svenstaro/prj/innojam9/build-web/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named innojam9

# Build rule for target.
innojam9: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 innojam9
.PHONY : innojam9

# fast build rule for target.
innojam9/fast:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/build
.PHONY : innojam9/fast

#=============================================================================
# Target rules for targets named entityx

# Build rule for target.
entityx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 entityx
.PHONY : entityx

# fast build rule for target.
entityx/fast:
	$(MAKE) -f entityx/CMakeFiles/entityx.dir/build.make entityx/CMakeFiles/entityx.dir/build
.PHONY : entityx/fast

#=============================================================================
# Target rules for targets named entityx_shared

# Build rule for target.
entityx_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 entityx_shared
.PHONY : entityx_shared

# fast build rule for target.
entityx_shared/fast:
	$(MAKE) -f entityx/CMakeFiles/entityx_shared.dir/build.make entityx/CMakeFiles/entityx_shared.dir/build
.PHONY : entityx_shared/fast

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/main_state.o: src/main_state.cpp.o

.PHONY : src/main_state.o

# target to build an object file
src/main_state.cpp.o:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/main_state.cpp.o
.PHONY : src/main_state.cpp.o

src/main_state.i: src/main_state.cpp.i

.PHONY : src/main_state.i

# target to preprocess a source file
src/main_state.cpp.i:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/main_state.cpp.i
.PHONY : src/main_state.cpp.i

src/main_state.s: src/main_state.cpp.s

.PHONY : src/main_state.s

# target to generate assembly for a file
src/main_state.cpp.s:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/main_state.cpp.s
.PHONY : src/main_state.cpp.s

src/menu_state.o: src/menu_state.cpp.o

.PHONY : src/menu_state.o

# target to build an object file
src/menu_state.cpp.o:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/menu_state.cpp.o
.PHONY : src/menu_state.cpp.o

src/menu_state.i: src/menu_state.cpp.i

.PHONY : src/menu_state.i

# target to preprocess a source file
src/menu_state.cpp.i:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/menu_state.cpp.i
.PHONY : src/menu_state.cpp.i

src/menu_state.s: src/menu_state.cpp.s

.PHONY : src/menu_state.s

# target to generate assembly for a file
src/menu_state.cpp.s:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/menu_state.cpp.s
.PHONY : src/menu_state.cpp.s

src/patterns.o: src/patterns.cpp.o

.PHONY : src/patterns.o

# target to build an object file
src/patterns.cpp.o:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/patterns.cpp.o
.PHONY : src/patterns.cpp.o

src/patterns.i: src/patterns.cpp.i

.PHONY : src/patterns.i

# target to preprocess a source file
src/patterns.cpp.i:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/patterns.cpp.i
.PHONY : src/patterns.cpp.i

src/patterns.s: src/patterns.cpp.s

.PHONY : src/patterns.s

# target to generate assembly for a file
src/patterns.cpp.s:
	$(MAKE) -f CMakeFiles/innojam9.dir/build.make CMakeFiles/innojam9.dir/src/patterns.cpp.s
.PHONY : src/patterns.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... innojam9"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... entityx"
	@echo "... entityx_shared"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main_state.o"
	@echo "... src/main_state.i"
	@echo "... src/main_state.s"
	@echo "... src/menu_state.o"
	@echo "... src/menu_state.i"
	@echo "... src/menu_state.s"
	@echo "... src/patterns.o"
	@echo "... src/patterns.i"
	@echo "... src/patterns.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

